title: Justin Herman
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About me:</b>
  <br>
  Final semester student in Master in Data Science program at CUNY SPS. professional poker player since Sophomore year of college. Poker has given me an amazing opportunity 
	  to make a living in an area that most people can only envision as a hobby. I am passionate about data and eager to start my journey in the field of data science 
<br>  <br>  <br>
  <b>Languages</b>
  <br>  <br>  <br>
  R,Python,SQL
  <br>  <br>  <br>
  <b>Skills</b>
  <br>
  Data exploration, Data Manipulation, Data Modeling, Supervised and Unsupervised Learning<br>
  <br>  <br>  <br>
  <b>Topics of Interest</b>
  <br>
  Time Series, NLP, Predictive Modeling
  <br>
  <br>
  <a href="https://www.linkedin.com/in/justin-herman-3930b817b/">View My LinkedIn Profile</a> 
  
theme: "jekyll-theme-minimal"
minimal_mistakes_skin: 'dark'
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
