title: Justin Herman
logo: "/images/profile_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About me:</b>
  <br>
  I am currently entering into the last semester of my Master in Data Science program <br> 
  I have been a profesional poker player since sophmore year of college. Poker has given me an amazing oppurtunity 
  to make a living in an area that most people can only envision as a hobby. 
  <br>
  I am pasisonate about data and eager to start my journey in the field of data science 
  <br>
  <b>Languages</b>
  <br>
  R,Python,SQL
  <br>
  <b>Skills</b>
  <br>
  Data exploration, Data Manipulation, Data Modeling, Supervised and Unsupervised Learning<br>
  <br>
  <b>Topics of Interest</b>
  Time Series, NLP, Predictive Modeling
  <br>
  <a href="https://www.linkedin.com/in/justin-herman-3930b817b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
